title: "Signals of Thought"
#email: m.s.s.ameen7@gmail.com

baseurl: "/my-site" # the subpath of your site, e.g. /blog
url: "https://mohamedsameen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  mohamedsameen

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "valdezmatt/jekyll-theme-basically-science"

sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache


markdown: kramdown
highlighter: rouge


header_pages: 
  - about.md
  - blog/index.md
  - research.md
  - projects.md

collections:
  research:
    output: true
    permalink: /research/:title/
    
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/


    
  # Keep other existing links...
  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
